name 'mysql_demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mysql'
long_description 'Installs/Configures mysql'
version '0.1.1'

depends 'mysql', '~> 7.0'
depends 'mysql2_chef_gem', '~> 1.1'
depends 'database', '~> 6.0'
